## API Connection Test

In [1]:
import requests
import pandas as pd
API_KEY = 'm5GkXnwARzqdEwbw5DCzW9UdiNlFnpFt'

def fetch_option_chain(symbol):
    url = f"https://api.polygon.io/v3/snapshot/options/{symbol}?apiKey=m5GkXnwARzqdEwbw5DCzW9UdiNlFnpFt"
    r = requests.get(url)
    r.raise_for_status()
    data = r.json()

    return data

    # options = []

    # for contract in data["results"]:
    #     options.append({
    #         "strike": contract["details"]["strike_price"],
    #         "type": contract["details"]["contract_type"],
    #         "price": (contract["last_quote"]["bid"] +
    #                   contract["last_quote"]["ask"]) / 2
    #     })

    # return pd.DataFrame(options)

nvda = fetch_option_chain('NVDA')
nvda

{'results': [{'day': {'change': 3.26,
    'change_percent': 2.274,
    'close': 146.64,
    'high': 147,
    'last_updated': 1771995600000000000,
    'low': 144.82,
    'open': 145.11,
    'previous_close': 143.38,
    'volume': 18,
    'vwap': 145.7222},
   'details': {'contract_type': 'call',
    'exercise_style': 'american',
    'expiration_date': '2026-02-27',
    'shares_per_contract': 100,
    'strike_price': 50,
    'ticker': 'O:NVDA260227C00050000'},
   'greeks': {},
   'open_interest': 24,
   'underlying_asset': {'ticker': 'NVDA'}},
  {'day': {'change': 0,
    'change_percent': 0,
    'close': 134.25,
    'high': 134.25,
    'last_updated': 1771621200000000000,
    'low': 134.25,
    'open': 134.25,
    'previous_close': 134.25,
    'volume': 1,
    'vwap': 134.25},
   'details': {'contract_type': 'call',
    'exercise_style': 'american',
    'expiration_date': '2026-02-27',
    'shares_per_contract': 100,
    'strike_price': 55,
    'ticker': 'O:NVDA260227C00055000'},
   'greeks': {},
   'open_interest': 7,
   'underlying_asset': {'ticker': 'NVDA'}},
  {'day': {'change': 7.46,
    'change_percent': 5.768,
    'close': 136.8,
    'high': 137.1,
    'last_updated': 1771995600000000000,
    'low': 135.04,
    'open': 135.04,
    'previous_close': 129.34,
    'volume': 12,
    'vwap': 135.3583},
   'details': {'contract_type': 'call',
    'exercise_style': 'american',
    'expiration_date': '2026-02-27',
    'shares_per_contract': 100,
    'strike_price': 60,
    'ticker': 'O:NVDA260227C00060000'},
   'greeks': {},
   'open_interest': 47,
   'underlying_asset': {'ticker': 'NVDA'}},
  {'day': {'change': 6.48,
    'change_percent': 5.171,
    'close': 131.8,
    'high': 132.69,
    'last_updated': 1771995600000000000,
    'low': 131.8,
    'open': 132.35,
    'previous_close': 125.32,
    'volume': 4,
    'vwap': 132.235},
   'details': {'contract_type': 'call',
    'exercise_style': 'american',
    'expiration_date': '2026-02-27',
    'shares_per_contract': 100,
    'strike_price': 65,
    'ticker': 'O:NVDA260227C00065000'},
   'greeks': {'delta': 0.9993217976256761,
    'gamma': 3.1002145078328615e-05,
    'theta': -0.046071910818111635,
    'vega': 0.0006903198102356205},
   'implied_volatility': 4.891132645932114,
   'open_interest': 5,
   'underlying_asset': {'ticker': 'NVDA'}},
  {'day': {'change': 7.13,
    'change_percent': 5.931,
    'close': 127.35,
    'high': 127.35,
    'last_updated': 1771995600000000000,
    'low': 127.35,
    'open': 127.35,
    'previous_close': 120.22,
    'volume': 1,
    'vwap': 127.35},
   'details': {'contract_type': 'call',
    'exercise_style': 'american',
    'expiration_date': '2026-02-27',
    'shares_per_contract': 100,
    'strike_price': 70,
    'ticker': 'O:NVDA260227C00070000'},
   'greeks': {},
   'open_interest': 23,
   'underlying_asset': {'ticker': 'NVDA'}},
  {'day': {'change': 3.57,
    'change_percent': 3.054,
    'close': 120.47,
    'high': 120.47,
    'last_updated': 1771995600000000000,
    'low': 120.47,
    'open': 120.47,
    'previous_close': 116.9,
    'volume': 1,
    'vwap': 120.47},
   'details': {'contract_type': 'call',
    'exercise_style': 'american',
    'expiration_date': '2026-02-27',
    'shares_per_contract': 100,
    'strike_price': 75,
    'ticker': 'O:NVDA260227C00075000'},
   'greeks': {},
   'open_interest': 4,
   'underlying_asset': {'ticker': 'NVDA'}},
  {'day': {'change': 0,
    'change_percent': 0,
    'close': 113,
    'high': 113,
    'last_updated': 1771966800000000000,
    'low': 112.6,
    'open': 112.6,
    'previous_close': 113,
    'volume': 2,
    'vwap': 112.8},
   'details': {'contract_type': 'call',
    'exercise_style': 'american',
    'expiration_date': '2026-02-27',
    'shares_per_contract': 100,
    'strike_price': 80,
    'ticker': 'O:NVDA260227C00080000'},
   'greeks': {},
   'open_interest': 11,
   'underlying_asset': {'ticker': 'NVDA'}},
  {'day': {'change': 7.13,
    'change_percent': 6.754,
    'close': 112.69,
    'high': 112.69,
    'last_updated': 1771995600000000000,
    'low': 110.28,
    'open': 110.28,
    'previous_close': 105.56,
    'volume': 46,
    'vwap': 110.5565},
   'details': {'contract_type': 'call',
    'exercise_style': 'american',
    'expiration_date': '2026-02-27',
    'shares_per_contract': 100,
    'strike_price': 85,
    'ticker': 'O:NVDA260227C00085000'},
   'greeks': {'delta': 0.9940017062547472,
    'gamma': 0.00023398404128477477,
    'theta': -0.2860407325901479,
    'vega': 0.002173497472666249},
   'implied_volatility': 4.710945974702384,
   'open_interest': 68,
   'underlying_asset': {'ticker': 'NVDA'}},
  {'day': {'change': 9.45,
    'change_percent': 9.643,
    'close': 107.45,
    'high': 107.45,
    'last_updated': 1771995600000000000,
    'low': 107.45,
    'open': 107.45,
    'previous_close': 98,
    'volume': 1,
    'vwap': 107.45},
   'details': {'contract_type': 'call',
    'exercise_style': 'american',
    'expiration_date': '2026-02-27',
    'shares_per_contract': 100,
    'strike_price': 90,
    'ticker': 'O:NVDA260227C00090000'},
   'greeks': {'delta': 0.9999988045944181,
    'gamma': -4.312033666783928e-08,
    'theta': -0.008913120896205004,
    'vega': 1.8191332170582722e-05},
   'implied_volatility': 0.0005242316506930133,
   'open_interest': 34,
   'underlying_asset': {'ticker': 'NVDA'}},
  {'day': {'change': 0,
    'change_percent': 0,
    'close': 96.65,
    'high': 96.65,
    'last_updated': 1771966800000000000,
    'low': 96.4,
    'open': 96.4,
    'previous_close': 96.65,
    'volume': 4,
    'vwap': 96.525},
   'details': {'contract_type': 'call',
    'exercise_style': 'american',
    'expiration_date': '2026-02-27',
    'shares_per_contract': 100,
    'strike_price': 95,
    'ticker': 'O:NVDA260227C00095000'},
   'greeks': {'delta': 0.9980486452544133,
    'gamma': 0.00011467263407510216,
    'theta': -0.08331620030775092,
    'vega': 0.0008413974898770696},
   'implied_volatility': 3.474120979192886,
   'open_interest': 17,
   'underlying_asset': {'ticker': 'NVDA'}}],
 'status': 'OK',
 'request_id': '3318f3e584712853a10c40e7d86dde80',
 'next_url': 'https://api.polygon.io/v3/snapshot/options/NVDA?cursor=YXA9TyUzQU5WREEyNjAyMjdDMDAwOTUwMDAlM0E5NS4wMCZhcz0mZXhwaXJhdGlvbl9kYXRlLmd0ZT0yMDI2LTAyLTI3JmxpbWl0PTEwJnNvcnQ9dGlja2Vy'}

In [2]:
from massive import RESTClient

client = RESTClient("m5GkXnwARzqdEwbw5DCzW9UdiNlFnpFt")

options_data = []
for o in client.list_snapshot_options_chain(
    "NVDA",
    params={
        "order": "asc",
        "limit": 10,
        "sort": "ticker",
    },
):
    options_data.append({
        "ticker": o.details.ticker,
        "contract_type": o.details.contract_type,
        "strike_price": o.details.strike_price,
        "expiration_date": o.details.expiration_date,
        "underlying_ticker": o.underlying_asset.ticker,
        "open_interest": o.open_interest,
        "close": o.day.close if o.day else None,
        "volume": o.day.volume if o.day else None,
        "implied_volatility": o.implied_volatility,
        "last_updated": o.day.last_updated
    })

options_chain = pd.DataFrame(options_data)
options_chain

,ticker,contract_type,strike_price,expiration_date,underlying_ticker,open_interest,close,volume,implied_volatility,last_updated
0,O:NVDA260227C00050000,call,50.0,2026-02-27,NVDA,24,146.64,18.0,NaN,1.771996e+18
1,O:NVDA260227C00055000,call,55.0,2026-02-27,NVDA,7,134.25,1.0,NaN,1.771621e+18
2,O:NVDA260227C00060000,call,60.0,2026-02-27,NVDA,47,136.80,12.0,NaN,1.771996e+18
3,O:NVDA260227C00065000,call,65.0,2026-02-27,NVDA,5,131.80,4.0,4.470160,1.771996e+18
4,O:NVDA260227C00070000,call,70.0,2026-02-27,NVDA,23,127.35,1.0,NaN,1.771996e+18
...,...,...,...,...,...,...,...,...,...,...
3441,O:NVDA281215P00340000,put,340.0,2028-12-15,NVDA,525,157.07,2.0,0.455098,1.771967e+18
3442,O:NVDA281215P00350000,put,350.0,2028-12-15,NVDA,278,161.70,2.0,0.453868,1.771996e+18
3443,O:NVDA281215P00360000,put,360.0,2028-12-15,NVDA,372,174.25,1.0,0.451330,1.771967e+18
3444,O:NVDA281215P00370000,put,370.0,2028-12-15,NVDA,321,183.29,2.0,0.449581,1.771967e+18
3445,O:NVDA281215P00380000,put,380.0,2028-12-15,NVDA,428,192.24,2.0,0.450003,1.771967e+18

In [3]:
options_chain[options_chain['last_updated'].isnull()]

,ticker,contract_type,strike_price,expiration_date,underlying_ticker,open_interest,close,volume,implied_volatility,last_updated
123,O:NVDA260227P00255000,put,255.0,2026-02-27,NVDA,0,NaN,NaN,1.847705,NaN
132,O:NVDA260227P00300000,put,300.0,2026-02-27,NVDA,0,NaN,NaN,2.759194,NaN
133,O:NVDA260227P00305000,put,305.0,2026-02-27,NVDA,0,NaN,NaN,2.818471,NaN
134,O:NVDA260227P00310000,put,310.0,2026-02-27,NVDA,0,NaN,NaN,2.902403,NaN
136,O:NVDA260227P00330000,put,330.0,2026-02-27,NVDA,0,NaN,NaN,3.275189,NaN
...,...,...,...,...,...,...,...,...,...,...
2175,O:NVDA261120P00320000,put,320.0,2026-11-20,NVDA,0,NaN,NaN,0.439350,NaN
2176,O:NVDA261120P00330000,put,330.0,2026-11-20,NVDA,0,NaN,NaN,0.444902,NaN
2177,O:NVDA261120P00340000,put,340.0,2026-11-20,NVDA,0,NaN,NaN,0.453385,NaN
2852,O:NVDA270319P00280000,put,280.0,2027-03-19,NVDA,0,NaN,NaN,0.440775,NaN
2860,O:NVDA270319P00360000,put,360.0,2027-03-19,NVDA,0,NaN,NaN,0.443882,NaN

In [4]:
options_chain[options_chain.duplicated(subset=['ticker'], keep=False)]

Empty DataFrame
Columns: [ticker, contract_type, strike_price, expiration_date, underlying_ticker, open_interest, close, volume, implied_volatility, last_updated]
Index: []

In [1]:
import requests
import json

API_KEY = "m5GkXnwARzqdEwbw5DCzW9UdiNlFnpFt"

url = f"https://api.polygon.io/v3/snapshot/options/NVDA?apiKey={API_KEY}"

data = requests.get(url).json()

# print first contract fully formatted
print(json.dumps(data["results"][0], indent=2))

{
  "day": {
    "change": -10.3,
    "change_percent": -7,
    "close": 136.8,
    "high": 139.55,
    "last_updated": 1772082000000000000,
    "low": 136.59,
    "open": 139.55,
    "previous_close": 147.09,
    "volume": 12,
    "vwap": 139.0742
  },
  "details": {
    "contract_type": "call",
    "exercise_style": "american",
    "expiration_date": "2026-02-27",
    "shares_per_contract": 100,
    "strike_price": 50,
    "ticker": "O:NVDA260227C00050000"
  },
  "greeks": {
    "delta": 0.9928050274626916,
    "gamma": 0.00017220495949434186,
    "theta": -0.9211488412884965,
    "vega": 0.002747081386775225
  },
  "implied_volatility": 10.588456844336978,
  "open_interest": 32,
  "underlying_asset": {
    "ticker": "NVDA"
  }
}

## Database Connection Test

In [1]:
import sqlite3

conn = sqlite3.connect("../data/options.db")
cursor = conn.cursor()

print("Connected successfully.")

Connected successfully.

In [2]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")

tables = cursor.fetchall()

print(tables)

[('contracts',), ('snapshots',)]

In [4]:
import pandas as pd

df = pd.read_sql_query("SELECT * FROM snapshots", conn)

df

,snapshot_time,contract_symbol,underlying_symbol,day_change,day_change_percent,day_close,day_high,day_low,day_open,day_previous_close,day_volume,day_vwap,day_last_updated_ns,day_last_updated_utc,delta,gamma,theta,vega,implied_volatility,open_interest
0,2026-02-24T22:23:14.549527+00:00,O:NVDA260227C00050000,NVDA,2.13,1.508,143.38,143.38,140.02,140.02,141.25,2,141.7000,1771909200000000000,2026-02-24T05:00:00+00:00,0.996293,0.000100,-0.200187,0.001899,6.190728,22
1,2026-02-24T22:23:14.549527+00:00,O:NVDA260227C00055000,NVDA,0.00,0.000,134.25,134.25,134.25,134.25,134.25,1,134.2500,1771621200000000000,2026-02-20T21:00:00+00:00,0.982533,0.000308,-0.978347,0.009068,7.840966,7
2,2026-02-24T22:23:14.549527+00:00,O:NVDA260227C00060000,NVDA,-1.39,-1.060,129.34,129.34,129.34,129.34,130.73,1,129.3400,1771909200000000000,2026-02-24T05:00:00+00:00,0.981167,0.000352,-0.973765,0.009552,7.321486,47
3,2026-02-24T22:23:14.549527+00:00,O:NVDA260227C00065000,NVDA,0.00,0.000,125.32,126.54,125.32,126.27,125.32,5,126.0060,1771880400000000000,2026-02-23T21:00:00+00:00,0.979754,0.000401,-0.968148,0.010015,6.846817,5
4,2026-02-24T22:23:14.549527+00:00,O:NVDA260227C00070000,NVDA,-0.27,-0.224,120.22,120.22,120.15,120.15,120.49,2,120.1850,1771909200000000000,2026-02-24T05:00:00+00:00,0.995199,0.000166,-0.193205,0.002286,4.685947,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46879,2026-02-26T18:49:21.969785+00:00,O:TSLA281215P00700000,TSLA,0.00,0.000,323.90,323.90,323.90,323.90,323.90,1,323.9000,1772053200000000000,2026-02-25T21:00:00+00:00,-0.624955,0.001595,-0.035696,2.488885,0.508447,14
46880,2026-02-26T18:49:21.969785+00:00,O:TSLA281215P00720000,TSLA,-6.79,-1.960,339.85,340.35,339.85,340.25,346.64,64,340.0313,1772082000000000000,2026-02-26T05:00:00+00:00,-0.643439,0.001616,-0.035103,2.436808,0.510033,25
46881,2026-02-26T18:49:21.969785+00:00,O:TSLA281215P00770000,TSLA,0.00,0.000,381.50,381.50,380.50,380.75,381.50,40,380.8563,1772053200000000000,2026-02-25T21:00:00+00:00,-0.685034,0.001637,-0.031402,2.040731,0.512812,71
46882,2026-02-26T18:49:21.969785+00:00,O:TSLA281215P00790000,TSLA,0.00,0.000,398.90,399.11,398.90,398.90,398.90,23,398.9813,1772053200000000000,2026-02-25T21:00:00+00:00,-0.701009,0.001635,-0.028350,1.884933,0.511551,59
46883,2026-02-26T18:49:21.969785+00:00,O:TSLA281215P00850000,TSLA,0.00,0.000,451.60,451.60,451.60,451.60,451.60,1,451.6000,1772053200000000000,2026-02-25T21:00:00+00:00,-0.757383,0.001744,-0.025246,1.909634,0.506669,23

In [5]:
df[df.duplicated(subset=['contract_symbol'], keep=False)]

,snapshot_time,contract_symbol,underlying_symbol,day_change,day_change_percent,day_close,day_high,day_low,day_open,day_previous_close,day_volume,day_vwap,day_last_updated_ns,day_last_updated_utc,delta,gamma,theta,vega,implied_volatility,open_interest
0,2026-02-24T22:23:14.549527+00:00,O:NVDA260227C00050000,NVDA,2.13,1.508,143.38,143.38,140.02,140.02,141.25,2,141.700,1771909200000000000,2026-02-24T05:00:00+00:00,0.996293,0.000100,-0.200187,0.001899,6.190728,22
2,2026-02-24T22:23:14.549527+00:00,O:NVDA260227C00060000,NVDA,-1.39,-1.060,129.34,129.34,129.34,129.34,130.73,1,129.340,1771909200000000000,2026-02-24T05:00:00+00:00,0.981167,0.000352,-0.973765,0.009552,7.321486,47
3,2026-02-24T22:23:14.549527+00:00,O:NVDA260227C00065000,NVDA,0.00,0.000,125.32,126.54,125.32,126.27,125.32,5,126.006,1771880400000000000,2026-02-23T21:00:00+00:00,0.979754,0.000401,-0.968148,0.010015,6.846817,5
4,2026-02-24T22:23:14.549527+00:00,O:NVDA260227C00070000,NVDA,-0.27,-0.224,120.22,120.22,120.15,120.15,120.49,2,120.185,1771909200000000000,2026-02-24T05:00:00+00:00,0.995199,0.000166,-0.193205,0.002286,4.685947,25
5,2026-02-24T22:23:14.549527+00:00,O:NVDA260227C00075000,NVDA,0.98,0.845,116.90,116.90,116.90,116.90,115.92,1,116.900,1771909200000000000,2026-02-24T05:00:00+00:00,0.976744,0.000514,-0.954494,0.010883,6.005242,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6479,2026-02-25T18:48:53.291828+00:00,O:NVDA281215P00250000,NVDA,-2.50,-2.860,85.00,85.00,85.00,85.00,87.50,5,85.000,1771995600000000000,2026-02-25T05:00:00+00:00,-0.467268,0.003182,-0.018991,1.289514,0.463790,318
6480,2026-02-25T18:48:53.291828+00:00,O:NVDA281215P00290000,NVDA,-2.26,-1.930,114.54,114.54,114.54,114.54,116.80,1,114.540,1771995600000000000,2026-02-25T05:00:00+00:00,-0.569456,0.003528,-0.016427,1.223464,0.454408,406
6481,2026-02-25T18:48:53.291828+00:00,O:NVDA281215P00300000,NVDA,-3.10,-2.500,121.10,122.40,121.10,122.40,124.20,94,121.715,1771995600000000000,2026-02-25T05:00:00+00:00,-0.593908,0.003572,-0.015475,1.204661,0.453425,2538
6482,2026-02-25T18:48:53.291828+00:00,O:NVDA281215P00330000,NVDA,-3.24,-2.180,145.41,146.31,145.41,146.31,148.65,6,145.860,1771995600000000000,2026-02-25T05:00:00+00:00,-0.667798,0.003792,-0.014113,1.158487,0.453931,712
6483,2026-02-25T18:48:53.291828+00:00,O:NVDA281215P00350000,NVDA,-3.72,-2.250,161.70,162.10,161.70,162.10,165.42,2,161.900,1771995600000000000,2026-02-25T05:00:00+00:00,-0.712889,0.003834,-0.011756,0.896669,0.452680,278

## Find All Iron Condors

In [ ]:
import sqlite3

conn = sqlite3.connect("../data/options.db")
cursor = conn.cursor()

print("Connected successfully.")

In [17]:
import sys
sys.path.append('..')

import importlib
import condors
importlib.reload(condors)

from condors import find_all_iron_condors_bs
qqq = find_all_iron_condors_bs('QQQ', '2026-02-25', '2026-03-20', 0.0368, conn)

175420266

In [14]:
qqq

,expected_value,pop,net_credit,max_risk,return_on_risk,put_iv,call_iv,liquidity,net_delta,net_gamma,net_theta,net_vega
0,-0.0386,0.0,1.9555,0.0386,50.660622,0.208501,0.206993,873,-0.000720,-0.000024,0.005910,0.000110
1,-0.2280,0.0,1.7661,0.2280,7.746053,0.208501,0.186394,873,-0.002554,-0.000197,0.002249,0.000350
2,-0.2337,0.0,1.7604,0.2337,7.532734,0.208501,0.189295,873,-0.002516,-0.000156,0.003026,0.000343
3,-0.2545,0.0,1.5118,0.2545,5.940275,0.195612,0.189295,349,-0.000906,-0.000102,-0.001754,0.000143
4,-0.2545,0.0,1.5175,0.2545,5.962672,0.195612,0.186394,349,-0.000944,-0.000143,-0.002530,0.000150
...,...,...,...,...,...,...,...,...,...,...,...,...
55071608,-425.3600,0.0,69.6500,425.3600,0.163744,0.270876,0.240416,0,0.988042,-0.001789,0.015264,-0.042722
55071609,-425.3600,0.0,69.6500,425.3600,0.163744,0.270876,0.240416,0,0.988011,-0.001793,0.015257,-0.042716
55071610,-425.3600,0.0,69.6450,425.3600,0.163732,0.270876,0.240416,0,0.987982,-0.001797,0.015250,-0.042710
55071611,-425.3600,0.0,69.6500,425.3600,0.163744,0.270876,0.240416,0,0.987955,-0.001801,0.015243,-0.042704
55071612,-425.3600,0.0,69.6500,425.3600,0.163744,0.270876,0.193257,0,0.986892,-0.001914,0.016964,-0.053048

In [12]:
qqq = qqq[qqq['liquidity'] != 0]
qqq

Empty DataFrame
Columns: [expected_value, pop, net_credit, max_risk, return_on_risk, put_iv, call_iv, liquidity]
Index: []

In [16]:
qqq['pop'].describe()

count    5.507161e+07
mean     1.359692e-05
std      3.287490e-04
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.356774e-02
Name: pop, dtype: float64